# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-11-25 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateapp', '0002_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prof_pic',
            field=models.ImageField(default='/prof_pics/default.png', upload_to='prof_pics/'),
        ),
    ]
