# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-11-25 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rateapp', '0003_auto_20191125_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='prof_pic',
            field=models.ImageField(default='/prof_pics/default.png', null=True, upload_to='prof_pics/'),
        ),
    ]
